name = "example"
main = "src/index.ts"
compatibility_date = "2023-04-02"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [{ binding = "LD_KV", id = "616aadb3c9474693bb9faaa4e53ea40c", preview_id = "88c3bd2abe5a4c3eb9b95829b86c2449" }]
